const ComplimentesGood = [
    "Tak trzymaj!",
    "Nie zatrzymuj się",
    "Taki nastrój Ci pasuje",
    "Jest Ci do twarzy gdy masz dobry humor",
    "Zdecydowanie lepiej mieć dobry humor, czyż nie?",
    "Z dobrym humorem o jest o wiele lepiej",
    "Szczęscie jest decyzją, nie punktem na mapie.",
    "Poddający się - nigdy nie wygrywa, a wygrywający - nigdy się nie poddaje.",   
    "Najlepszą metodą przewidywania przyszłości jest jej tworzenie.",
    "Jeśli jesteś gotów robić tylko to co jest łatwe, życie będzie trudne. Ale jeśli jesteś gotów robić to co jest trudne, życie będzie łatwe.",
    "Im więcej potu na poligonie, tym mniej krwi na polu boju.",
    "Podczas, gdy większość marzy o sukcesie - zwycięzcy budzą się i ciężko pracują, aby go osiągnąć.",
    "To niesamowite, ile można osiągnąć, jeśli nie dba się o to, na kogo spadną zaszczyty.",
    "Ten, kto zwycięża innych jest silny. Ten, kto zwycięża samego siebie jest potężny.",
    "Szczęśliwym człowiekiem jest ten, który potrafi zbudować solidne fundamenty z cegieł, które inni rzucają w niego.",
    "Kiedy staje się oczywiste, że cele nie mogą zostać osiągnięte - nie dostosowuj celów, dostosuj działania.",
    'Miej podejście właściwe studentom: nigdy nie bądź zbyt wielkim, by zadawać pytania, nigdy nie wiedz zbyt dużo, by nauczyć się czegoś nowego.',
    'Choć nikt nie może cofnąć się w czasie i zmienić początku na zupełnie inny, to każdy może zacząć dziś i stworzyć całkiem nowe zakończenie.',
    'Zacznij od robienia tego, co konieczne, potem zrób to, co możliwe, nagle odkryjesz, że dokonałeś niemożliwego.',
    'Sukces to drabina, po której nie sposób wspiąć się z rękami w kieszeniach.',
    'Statek w porcie jest bezpieczny, ale nie po to buduje się statki.',
    'Szaleństwem jest robić wciąż to samo i oczekiwać różnych rezultatów.',
    'Jeśli w życiu brakuje miejsca na odwagę, to inne cnoty są bez znaczenia.',
    'Życie jest długie i nudne, jeśli nie przeżywa się go tak, jakby się chciało.',
    'Aby zapalać innych, samemu trzeba płonąć.',
    'Sposobem na zaczęcie jest skończenie mówienia i podjęcie działania.',
    'Nie bój się dużego kroku. Nie pokonasz przepaści dwoma małymi.',
    'Umysły są jak spadochrony – działają tylko gdy są otwarte.',
    'Tylko głupiec nie ma wątpliwości.',
    'Początek jest najważniejszą częścią pracy.',
    'Nie oczekujcie od dnia tego, co mogą dać jedynie lata. Ale nie zapominajcie, że lata składają się z wielu dni, dlatego postanówcie, że nie zmarnujecie ani jednego dnia.',
    'Nic, co ma wielką wartość w życiu nie przychodzi łatwo.',
    'Ludzie, którzy tracą czas, czekając aż zaistnieją najbardziej sprzyjające warunki, nigdy nic nie zdziałają.',
    'Cel to nic innego, jak marzenie z terminem realizacji.',
    'To nie to, co masz, ani to, kim jesteś, ani to, gdzie jesteś, ani co robisz czyni Cię szczęśliwym bądź nieszczęśliwym. Chodzi o to, o czym myślisz.',
    'Czy jest ktoś, kogo chciałbyś zmienić, poinstruować, ulepszyć? Świetnie! Jestem za! Ale dlaczego nie zaczniesz od siebie?',
    'W dwa miesiące możesz zdobyć więcej przyjaciół, interesując się innymi ludźmi, niż w ciągu dwóch lat, usiłując zainteresować sobą innych.',
    'Życie to 10% tego, co nam się przydarza i 90% tego, jak na to reagujemy. Nasze podejście jest wszystkim.',
    'Gdy nie wiesz, do którego portu płyniesz, żaden wiatr nie jest dobry.',
    'Sukces nie jest kluczem do szczęścia, ale szczęście jest kluczem do sukcesu.',
    'Krytykować, potępiać i narzekać potrafi każdy głupiec – i większość głupców tak robi. Ale aby zrozumieć i darować, potrzeba charakteru i samokontroli.',
    'Czasami od myślenia odstrasza nas nie związany z nim wysiłek, lecz wnioski, do jakich moglibyśmy dojść.',
    'Nie znam klucza do sukcesu, ale kluczem do klęski jest próba zadowolenia wszystkich.',
    'Pomysły są powszechnym towarem. Wprowadzanie ich w życie nie jest.',
    'Skoro i tak będziesz myśleć, myśl odważnie.',
    'Istnieją tylko dwa dni w roku, w których nic nie może być zrobione. Jeden nazywamy "wczoraj", a drugi "jutro". "Dzisiaj" to właściwy dzień, aby kochać, wierzyć i żyć w pełni.',
    '“Kiedyś” to choroba, która każe nam zabrać wszystkie nasze marzenia do grobu.Tim Ferriss',
    'Nie chcę pod koniec życia stwierdzić, że przeżyłam tylko jego długość. Chcę przeżyć też pełną jego szerokość.',
    'A jak wyjdzie śmiesznie? Ludzie się pośmieją i koniec. Wielkość nie boi się śmieszności.',
    'Motywacja pozwala wystartować. Nawyk utrzymuje w ruchu.',
    'Widzimy ludzi, którzy zgromadzili wielkie fortuny ale często oglądamy tylko ich triumf, pomijając porażki i przeszkody które spotykały ich po drodze.',
    'To, co powstrzymuje ludzi, to nie jakość ich pomysłów, tylko brak wiary w siebie.',
    'To, czego boimy się najbardziej, jest z reguły tym, co właśnie powinniśmy zrobić.',
    'Nie wystarczy być we właściwym czasie, we właściwym miejscu. Trzeba być jeszcze właściwie przygotowanym.',
    'Bądź tak dobry, by nie mogli Cię dłużej ignorować.Steve Martin',
    'Ludzie na ogół dają się łatwiej przekonać przez argumenty, na które sami wpadli, niż przez te, które ktoś im narzucił.',
    'Poświęcaj tyle czasu na ulepszanie siebie, byś nie miał go na krytykę innych.',
    'Jedynymi osobami, z którymi powinieneś wyrównać rachunki są ci, którzy Ci pomogli.',      
]
export default ComplimentesGood;