const ComplimentesBad = [
    "Pomyśl o czymś miłym",
    "Rozchmurz się",
    "Nie poddawaj się",
    "Złość piękności szkodzi",
    "Nie złośc się już",
    "Z każdej sytuacji da się wyjśc, pamiętaj aby myśleć pozytywnie",
    "Nie pasuje do Ciebie zły humor",
    "Zły nastruj nikomu nie służy",
    "Idź naprzód",
    "Nie przejmuj się",
    "Przypomnij sobie dobre chwile",
    "Istnieją tylko dwa dni w roku, w których nic nie może być zrobione. Jeden nazywamy wczoraj, a drugi jutro. Dzisiaj to właściwy dzień, aby kochać, wierzyć i żyć w pełni.",
    "Ludzie w większości przypadków poddają się wówczas, gdy są już na progu zwycięstwa. Rezygnują tuż przed metą. W ostatniej minucie gry, na metr przed linią, za którą jest zwycięstwo.",
    "Porażka jest po prostu okazją, by spróbować ponownie, tym razem bardziej przemyślanie.",
    "Nie bój się dużego kroku. Nie pokonasz przepaści dwoma małymi.",
    "Porażka jest dla nas szansą, aby mądrzej zacząć na nowo.",
    "Nic, co ma wielką wartość w życiu nie przychodzi łatwo.",
    "Sukces to nie kwestia wrodzonego talentu, błyskotliwej inteligencji ani szczęścia. Sukcesy odnoszą ludzie przekonani o tym, że wciąż mogą się wiele nauczyć.",
    "Bądź tak dobry, by nie mogli Cię dłużej ignorować.",
    "Najpoważniejsze błędy nie są rezultatem złych odpowiedzi. Naprawdę niebezpieczne rzeczy są spowodowane zadawaniem złych pytań.",
    "Cierpliwość, wytrwałość i pot tworzą niezrównaną kombinację do osiągnięcia sukcesu.",
    "Największą barierą w osiągnięciu sukcesu jest lęk przed porażką.",
    "Twoi najbardziej niezadowoleni klienci są Twoim największym źródłem nauki.",
    "Jeśli nie potrafisz robić wielkich rzeczy, rób małe rzeczy w wielki sposób.",
    "Aby odnieść sukces... Potrzebujesz znaleźć coś, czego będziesz się trzymał, coś co Cię zmotywuje i coś co Cię zainspiruje.",
    "Z nowym dniem przychodzi nowa siła i nowe myśli.",
    'Zrób to, zanim będziesz gotów, gdyż nigdy nie będziesz gotów, jeśli będziesz czekać.',
    'Wszystko, czego pragniesz jest po drugiej stronie strachu.',
    'Jesteś jedyną osobą na świecie, która może wykorzystać Twój potencjał.',
    'Zawsze zastanawiałem się, dlaczego ptaki zostają w tym samym miejscu, skoro mogą latać po całym świecie. Potem zadałem to samo pytanie sobie.',
    'Kto nie chce, kiedy może, ten nie będzie mógł, kiedy będzie chciał.',
    'Nigdy nie rezygnuj z celu tylko dlatego, że osiągnięcie go wymaga czasu. Czas i tak upłynie.',
    'Każdy artysta zaczynał kiedyś jako amator.',
    'Porażka jest po prostu okazją, by spróbować ponownie, tym razem bardziej przemyślanie.',
    'Nawet najdłuższa podróż zaczyna się od pierwszego kroku',
    'Nie popełnia błędu tylko ten, kto nic nie robi.',
    'Nie uda Ci się przepłynąć oceanu dopóki nie zdobędziesz odwagi, by stracić z oczu widok lądu.',
    'Poddający się - nigdy nie wygrywa, a wygrywający - nigdy się nie poddaje.',
    'Gdy zamykają się jedne drzwi do szczęścia, otwierają się inne, ale często tak długo patrzymy na zamknięte drzwi, że nie dostrzegamy tych, które zostały otwarte.',
    'Naszą największą słabością jest poddawanie się. Najpewniejszą drogą do sukcesu jest zawsze próbowanie jeden, kolejny raz.',
    'Gdy wszyscy wiedzą, że coś jest niemożliwe, przychodzi ktoś, kto o tym nie wie i to robi.',
    'Jeżeli uważasz, że możesz czegoś dokonać albo przeciwnie, że nie dasz rady - w obu przypadkach masz rację.',
    'Za dwadzieścia lat będziesz bardziej rozczarowany rzeczami, których nie zrobiłeś niż tymi, które zrobiłeś źle.',
    'Jest tylko jeden sposób na uniknięcie krytyki: nic nie robić, nic nie mówić i być nikim.',
    'Twój czas jest ograniczony, więc nie marnuj go na życie czyimś życiem.',
    'Nie martw się porażkami, martw się szansami, które tracisz, gdy nawet nie próbujesz.',
    'Jeśli nie potrafisz robić wielkich rzeczy, rób małe rzeczy w wielki sposób.',
    'Zawsze sie znajdzie odpowiednia filozofia do braku odwagi.',
    'Bądź wdzięczny za to, co masz, a będziesz miał tego więcej. Jeśli koncentrujesz się na tym, czego nie masz, nigdy nie będziesz miał wystarczająco dużo.',
    'Jesteśmy odzwierciedleniem pięciu osób, z którymi spędzamy najwięcej czasu. To oni nas motywują, doradzają, krytykują. Przyjrzyj się, z kim Ty przestajesz.',
    'O naszym szczęściu nie decyduje to, co nam się przydarza, ale to, jak na to reagujemy.',
    'Szczęscie jest decyzją, nie punktem na mapie.',
    'Powodem dla którego tak niewielu ludzi odnosi sukces jest to,że nikt nie wymyślił jeszcze sposobu umożliwiającego siedzenie i jednoczesne ślizganie się w górę.',
    'Sukces to nie kwestia wrodzonego talentu, błyskotliwej inteligencji ani szczęścia. Sukcesy odnoszą ludzie przekonani o tym, że wciąż mogą się wiele nauczyć.',
    'W życiu nie chodzi o czekanie, aż burza minie. Chodzi o to, by nauczyć się tańczyć w deszczu.',
    'Inspiracja istnieje, ale musi Cię zastać przy pracy.',
    'Jesteś odpowiedzialny nie tylko za to, co mówisz, ale również za to, czego nie mówisz.',
    'Nic nie jest szczególnie trudne do zrobienia, jeśli tylko rozłożyć to na etapy.',
]
export default ComplimentesBad;